[package]
name = "nrmu9/ro2dengine"
description = "A high-performance software rendering and physics engine utilizing EditableImage."
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
