#!/usr/bin/env python3
"""Ro2D Font Baker: compiles a TTF/OTF into a Luau ModuleScript bitmap font.

Renders the printable ASCII range into a packed RGBA atlas whose RGB is white and
whose alpha is glyph coverage, so `Draw.Text` can tint it per call. The emitted
module is consumed by `Ro2D.Assets.LoadFont`, which decodes the `Data` string via
`buffer.fromstring`.

Glyphs[byte] = {X, Y, W, H, Adv, OX, OY}: atlas rect, pen advance, and the draw
offset from the text origin (the ascender line).
"""

import argparse
import math
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("Error: Pillow is required. Install it with `pip install Pillow`.")

# Precomputed byte -> escape lookup; far faster than formatting per byte.
_ESCAPES = [f"\\x{i:02x}" for i in range(256)]

FIRST_GLYPH, LAST_GLYPH = 33, 126  # printable ASCII; space is handled by SpaceAdvance
ORIGIN = 4  # padding around the render canvas, also the text origin


def bake_font(input_path: str, output_path: str, name: str, size: int, atlas_width: int, pad: int) -> None:
    if not os.path.isfile(input_path):
        sys.exit(f"Error: Input font '{input_path}' not found.")

    try:
        font = ImageFont.truetype(input_path, size)
    except Exception as exc:  # noqa: BLE001
        sys.exit(f"Error opening font: {exc}")

    ascent, descent = font.getmetrics()
    tall = ascent + descent

    # Render each glyph to a coverage bitmap and record its tight bounding box.
    glyphs = {}
    for code in range(FIRST_GLYPH, LAST_GLYPH + 1):
        ch = chr(code)
        adv = font.getlength(ch)
        canvas = Image.new("L", (math.ceil(adv) + ORIGIN * 2, tall + ORIGIN * 2), 0)
        ImageDraw.Draw(canvas).text((ORIGIN, ORIGIN), ch, fill=255, font=font)
        bbox = canvas.getbbox()
        if bbox is None:  # blank glyph, nothing to pack
            continue
        left, top, right, bottom = bbox
        glyphs[code] = (canvas.crop(bbox), left - ORIGIN, top - ORIGIN,
                        right - left, bottom - top, round(adv))

    if not glyphs:
        sys.exit("Error: font produced no drawable glyphs.")

    # Shelf-pack the glyphs into a fixed-width atlas.
    x = y = row_height = 0
    placed = {}
    for code in sorted(glyphs):
        cover, ox, oy, w, h, adv = glyphs[code]
        if x + w + pad > atlas_width:
            x = 0
            y += row_height + pad
            row_height = 0
        placed[code] = (x, y, cover, ox, oy, w, h, adv)
        x += w + pad
        row_height = max(row_height, h)
    atlas_height = y + row_height + pad

    atlas = Image.new("RGBA", (atlas_width, atlas_height), (255, 255, 255, 0))
    for px, py, cover, _ox, _oy, w, h, _adv in placed.values():
        rgba = Image.new("RGBA", (w, h), (255, 255, 255, 0))
        rgba.putalpha(cover)
        atlas.paste(rgba, (px, py))

    # CapCenter: vertical middle of capitals, measured from the text top.
    cap_top = placed[ord("H")][4] if ord("H") in placed else 0
    cap_center = round((cap_top + ascent) / 2)
    space_advance = round(font.getlength(" "))

    data = "".join(map(_ESCAPES.__getitem__, atlas.tobytes()))
    lines = [
        "-- Auto-generated by Ro2D Font Baker. Do not edit.",
        "return {",
        f'\tName = "{name}",',
        f"\tWidth = {atlas_width},",
        f"\tHeight = {atlas_height},",
        f"\tLineHeight = {tall},",
        f"\tAscent = {ascent},",
        f"\tSpaceAdvance = {space_advance},",
        f"\tCapCenter = {cap_center},",
        "\tGlyphs = {",
    ]
    for code in sorted(placed):
        px, py, _cover, ox, oy, w, h, adv = placed[code]
        lines.append(f"\t\t[{code}] = {{X={px},Y={py},W={w},H={h}, Adv={adv}, OX={ox},OY={oy}}},")
    lines.append("\t},")
    lines.append(f'\tData = "{data}",')
    lines.append("}")

    try:
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
    except OSError as exc:
        sys.exit(f"Error writing file: {exc}")

    print(f"Success! Baked {len(placed)} glyphs into a {atlas_width}x{atlas_height} atlas "
          f"(ascent={ascent}, cap={cap_center}) at {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ro2D Font Baker: converts a TTF/OTF to a Luau bitmap-font module.")
    parser.add_argument("-i", "--input", required=True, help="Path to the input .ttf/.otf font")
    parser.add_argument("-o", "--output", required=True, help="Path to the output Luau file")
    parser.add_argument("-n", "--name", help="Font name recorded in the module (default: output filename stem)")
    parser.add_argument("-s", "--size", type=int, default=40, help="Native pixel size to rasterize at (default: 40)")
    parser.add_argument("--atlas-width", type=int, default=512, help="Atlas width in pixels (default: 512)")
    parser.add_argument("--pad", type=int, default=1, help="Transparent gutter between glyphs (default: 1)")
    args = parser.parse_args()

    font_name = args.name or os.path.splitext(os.path.basename(args.output))[0].lower()
    bake_font(args.input, args.output, font_name, args.size, args.atlas_width, args.pad)
