import argparse
import sys
import os
from PIL import Image

def convert_image(input_path, output_path):
    if not os.path.exists(input_path):
        print(f"Error: Input file '{input_path}' not found.")
        sys.exit(1)

    try:
        img = Image.open(input_path).convert("RGBA")
    except Exception as e:
        print(f"Error opening image: {e}")
        sys.exit(1)

    width, height = img.size
    pixels = img.tobytes()

    print(f"Processing {width}x{height} image ({len(pixels):,} bytes)...")

    lua_string = "".join([f"\\x{b:02x}" for b in pixels])
    lua_code = f"""-- Auto-generated by Ro2D Packer
local Asset = {{}}
Asset.Width = {width}
Asset.Height = {height}
Asset.Data = "{lua_string}"
return Asset
"""
    try:
        with open(output_path, "w") as f:
            f.write(lua_code)
        print(f"Success! Exported {len(lua_string):,} characters to {output_path}")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ro2D Asset Packer: Converts PNG to Lua Binary String")
    parser.add_argument("-i", "--input", required=True, help="Path to the input PNG image")
    parser.add_argument("-o", "--output", required=True, help="Path to the output Lua file")
    
    args = parser.parse_args()
    convert_image(args.input, args.output)