#!/usr/bin/env python3
"""Ro2D Asset Packer: compiles a PNG into a Luau ModuleScript holding raw RGBA bytes.

The engine reads the emitted `Data` string via `buffer.fromstring`, so we encode the
pixels as `\\xNN` escape sequences that Luau decodes back into the original bytes.
"""

import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Error: Pillow is required. Install it with `pip install Pillow`.")

# Precomputed byte -> escape lookup; far faster than formatting per byte.
_ESCAPES = [f"\\x{i:02x}" for i in range(256)]


def convert_image(input_path: str, output_path: str) -> None:
    if not os.path.isfile(input_path):
        sys.exit(f"Error: Input file '{input_path}' not found.")

    try:
        img = Image.open(input_path).convert("RGBA")
    except Exception as exc:  # noqa: BLE001
        sys.exit(f"Error opening image: {exc}")

    width, height = img.size
    pixels = img.tobytes()
    print(f"Processing {width}x{height} image ({len(pixels):,} bytes)...")

    data = "".join(map(_ESCAPES.__getitem__, pixels))
    module = (
        "-- Auto-generated by Ro2D Packer. Do not edit.\n"
        "return {\n"
        f"\tWidth = {width},\n"
        f"\tHeight = {height},\n"
        f'\tData = "{data}",\n'
        "}\n"
    )

    try:
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(module)
    except OSError as exc:
        sys.exit(f"Error writing file: {exc}")

    print(f"Success! Exported {len(data):,} characters to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Ro2D Asset Packer: converts a PNG to a Luau binary string module.")
    parser.add_argument("-i", "--input", required=True, help="Path to the input PNG image")
    parser.add_argument("-o", "--output", required=True, help="Path to the output Luau file")
    args = parser.parse_args()
    convert_image(args.input, args.output)
